### ISSUE TITLE
Basic insert-delete scenario fails with next version (ts)

### ISSUE THREAD

**Issue by oster** [coast-team/mute-structs#4]
A basic scenario that involves an insertion of a string followed by a deletion of a part of that string fails with the next (typescript) version of mute-structs. I added a test to illustrate that (see commit 422e9910feb818a9c4c1e4082666289c57c9d7d4)

**Comment by oster** [comment]
the provided test fails because document `str` attribute (string representing the linearized content of the structure) is different. 
According to the code, this is normal, since this attribute is never modified when executing 'remote' (logoots) operations. Currently, the solution is to apply the text operations obtained as a result of the execution of the logoots operation to the data-structure (without using the `applyTo`method since it will regenerate logoots operation...) 
This is weird, isn't it? 

The right question I guess, is do we need/want to keep the `str` attribute in the logootsropes data-structure?

Note that even if we omit the comparison of `str` attribute in the test, it still fails since `digest()` call crashes on `docA`! Therefore this issue should be split in two

**Comment by Conaclos** [comment]
This property (```str```) seems to be modified in [mute-client/coordinator](https://github.com/coast-team/mute-client/blob/master/lib/coordinator.js) for the remote operations.

It seem good at me to extract this from mute-struct and place this in a higher layer.

**Comment by Conaclos** [comment]
https://github.com/coast-team/mute-structs/commit/17f0853091eed092b1902a794c34447560315757 partially fixes this issue.

The precondition of ```IdentifierInterval``` class's constructor is no longer broke.

**Comment by oster** [comment]
According to different previous commit. Both issues (update of str attribute and crash during insert/del) are fixed now.
